### ISSUE TITLE
config mode registration

### ISSUE THREAD

**Issue by Swanarog** [Tuller/FlyPaper-2.0#1]
Could we include an option for addons to register a config mode toggle function, so that when one addon using flypaper activates config mode, it turns on all config modes for all addons using flypaper?

 I foresee this being able toggle on, but it would be up to the user to close each addon's config mode. This would be to prevent conflicts in the way each addon handles exiting their config modes.

**Comment by Tuller** [comment]
I think this one is beyond the scope of FlyPaper.
