### ISSUE TITLE
ClampRectInsets

### ISSUE THREAD

**Issue by Goranaws** [Tuller/FlyPaper-2.0#3]
Should ClampedRectInsets be taken into account for snapping purposes? I'm thinking xOffset and yOffset... Woke up in the middle of the night and couldn't fall back to sleep, so naturally this was the thought I had at 2am this morning.

https://wow.gamepedia.com/API_Frame_GetClampRectInsets

**Comment by Tuller** [comment]
Probably not for now. 

Its really only there for things where the size of the object doesn't actually match the interactable size. MicroMenuButtons are one of those cases, for example.

**Comment by Goranaws** [comment]
The micro menu buttons use hit rect insets, not clamp. And I have got to say that blizzard decided to design the micro menu buttons in a very odd style.

**Comment by Tuller** [comment]
Yep, you're right
